---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

services:
  - docker:dind

steps:
- name: build plugin
  image: gitlab/dind
  script:
  - docker build -t ${DRONE_REPO}:${DRONE_COMMIT:0:8}-linux-amd64
  - mkdir -p ./plugin/rootfs
  - docker create --name tmp ${DRONE_REPO}:${DRONE_COMMIT:0:8}-linux-amd64
  - docker export tmp | tar -x -C ./plugin/rootfs
  - docker rm -vf tmp
  - docker plugin create ${DRONE_REPO}:${DRONE_COMMIT:0:8}-linux-amd64 ./plugin