language: go

sudo: required

services:
  - docker

before_install:
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - sudo apt-get update
  - sudo apt-get install upx
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v4.2.0-7/qemu-aarch64-static.tar.gz -O /tmp/qemu-aarch64-static.tar.gz
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v4.2.0-7/qemu-arm-static.tar.gz -O /tmp/qemu-arm-static.tar.gz
  - tar zxvf /tmp/qemu-aarch64-static.tar.gz -C ./
  - tar zxvf /tmp/qemu-arm-static.tar.gz -C ./
  # Build Power(aarch64) Docker image
  - docker build -f Dockerfile.aarch64 -t cblomart/s3vol:edge-aarch64 .
  # Build Power(arm) Docker image
  - docker build -f Dockerfile.arm -t cblomart/s3vol:edge-arm .
  # Build Intel(amd64) Docker image
  - docker build -f Dockerfile -t cblomart/s3vol:edge-amd64 .

install: true

before_script: true

script: 
- docker images

after_script: true