language: go

sudo: required

services:
  - docker

before_install:
  - docker version
  - docker run --rm --privileged multiarch/qemu-user-static:register
  # Build Power(aarch64) Docker image
  - docker build -f Dockerfile.aarch64 -t cblomart/s3vol:edge-aarch64 .
  # Build Power(arm) Docker image
  - docker build -f Dockerfile.arm -t cblomart/s3vol:edge-arm .
  # Build Intel(amd64) Docker image
  - docker build -f Dockerfile -t cblomart/s3vol:edge-amd64 .

install: true

before_script: true

script: 
- docker images

after_script: true