FROM arm64v8/alpine:3.11

COPY qemu-aarch64-static /usr/bin

RUN apk add s3fs-fuse --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

COPY s3vol-arm64 /usr/local/bin/s3vol

#RUN rm -f /usr/bin/qemu-*-static

ENTRYPOINT [ "/usr/local/bin/s3vol" ]

CMD [ "serve" ]