FROM arm32v7/alpine:3.11

COPY qemu-arm-static /usr/bin

RUN apk add s3fs-fuse --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

COPY  s3vol-arm /usr/local/bin/s3vol

#RUN rm -f /usr/bin/qemu-*-static

ENTRYPOINT [ "/usr/local/bin/s3vol" ]

CMD [ "serve" ]